version: '2'
services:
  hustoj_frontend:
    container_name: hustoj_frontend
    build:
      context: .
      args:
        - VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
        - EXPOSE_PORT=${EXPOSE_PORT}
    env_file: ./.env
    ports:
      - "${EXPOSE_PORT}:${DOCKER_PORT}"
