version: '2'
services:
  hustoj_frontend:
    build:
      context: .
      args:
        - VUE_APP_BASE_URL=http://localhost:8081
    environment:
      - PORT=8080
    container_name: hustoj_frontend
    ports:
      - '8082:8080'
